---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Check if ubuntu-desktop is installed
    package_facts:
      manager: auto
  - name: Install tasksel
    apt:
      name: tasksel
      state: present
      update_cache: yes
    become: true
    when: not "ubuntu-desktop" in ansible_facts.packages
  - name: Install ubuntu desktop
    shell: tasksel install ubuntu-desktop
    become: true
    when: not "ubuntu-desktop" in ansible_facts.packages
    register: installdesktop
  - name: Reboot after installing desktop
    reboot:
    become: true
    when: installdesktop.changed

