---
- hosts: 127.0.0.1
- import_playbook: rust.yml
- import_playbook: dotnet.yml
  when: dotnet is undefined or dotnet != 'preview'
- import_playbook: dotnet_preview.yml
  when: dotnet == 'preview'
- import_playbook: desktop.yml
- import_playbook: vscode.yml
