---
- hosts: all
  tasks:
  - name: Make dotnet preview directory
    file:
      path: /tmp/dotnet_preview_6.rc2
      state: directory
      mode: '0755'
  - name: Download dotnet 6rc2 SDK (x86_64)
    when: ansible_architecture == 'x86_64'
    get_url:
      url: https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.100-rc.2.21505.57/dotnet-sdk-6.0.100-rc.2.21505.57-linux-x64.tar.gz
      dest: /tmp/dotnet_preview_6.rc2/dotnet.tar.gz
      checksum: sha512:0a8f85a2757f61ca7f9b8c546af4554c2aac9cdb06f6d62879a60de6f2a3d37ea7136f48896c9c85828a2d55df354e7b9b5b4dc22896c927f0c6370a5ade1b9c
  - name: Download dotnet 6rc2 SDK (ARM64)
    when: ansible_architecture == 'aarch64'
    get_url:
      url: https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.100-rc.2.21505.57/dotnet-sdk-6.0.100-rc.2.21505.57-linux-arm64.tar.gz
      dest: /tmp/dotnet_preview_6.rc2/dotnet.tar.gz
      checksum: sha512:14aa96f47f7f3520075e41753c705bdbf7f84fd7cff7cc2add1095a13e3e3c44eaaf2d822551902f05a6ad0c9acd7f7424190b7c09c397004c632eddc8acd5ac
  - name: Extract 6rc2 SDK
    shell: mkdir -p /usr/share/dotnet_preview && tar -C /usr/share/dotnet_preview -oxzf dotnet.tar.gz
    become: true
    args:
      chdir: /tmp/dotnet_preview_6.rc2
      creates: /usr/share/dotnet_preview/dotnet
  - name: Symlink dotnet executable
    file:
      src: /usr/share/dotnet_preview/dotnet
      dest: /usr/bin/dotnet
      state: link
    become: true
  - name: Set DOTNET_ROOT
    lineinfile:
      path: /etc/environment
      line: DOTNET_ROOT=/usr/share/dotnet_preview
    become: true

