---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Install clang
    apt:
      name: clang
      state: present
    become: true
  - name: Download rustup-init.sh
    get_url:
      url:  https://sh.rustup.rs
      dest: $HOME/rustup-init.sh
  - name: Run rustup-init
    shell: sh $HOME/rustup-init.sh -y
    args:
      creates: $HOME/.cargo/bin/rustup
