---
- hosts: all
  tasks:
  - name: Download Microsoft package signing key
    shell: wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
    become: true
  - name: Install Microsoft package signing key
    shell: install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/
    become: true
  - name: Cleanup downloaded signing key after installation
    shell: rm packages.microsoft.gpg
    become: true
  - name: Add vscode repo
    shell: sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
    become: true
  - name: Make sure HTTPS is supported by apt
    apt:
      name: apt-transport-https
      state: present
      update_cache: yes
    become: true
  - name: Install VS Code
    apt:
      name: code
      state: present
    become: true
  - name: Install Ionide to VS Code
    shell: code --install-extension ionide.ionide-fsharp
    args:
      creates: $HOME/.vscode/extensions/ionide.ionide-fsharp-*
  - name: Disable dependency on C# extension (ARM64 only)
    when: ansible_architecture == 'aarch64'
    shell: sed -i '/csharp/d' $HOME/.vscode/extensions/ionide.ionide-fsharp-*/package.json
  - name: Install Rust to VS Code
    shell: code --install-extension rust-lang.rust
    args:
      creates: $HOME/.vscode/extensions/rust-lang.rust-*
