---
- hosts: all
  tasks:
  - name: Add vscode repo
    apt_repository: 
      repo: deb https://packages.microsoft.com/repos/code stable main
      state: present
      update_cache: true
    become: true
  - name: Make sure HTTPS is supported by apt
    apt:
      name: apt-transport-https
      state: present
      update_cache: no
    become: true
  - name: Install VS Code
    apt:
      name: code
      state: present
    become: true
  - name: Install Ionide to VS Code
    shell: code --install-extension ionide.ionide-fsharp
    args:
      creates: $HOME/.vscode/extensions/ionide.ionide-fsharp-*
  - name: Disable dependency on C# extension (ARM64 only)
    when: ansible_architecture == 'aarch64'
    shell: sed -i '/csharp/d' .vscode/extensions/ionide.ionide-fsharp-*/package.json
  - name: Install Rust to VS Code
    shell: code --install-extension rust-lang.rust
    args:
      creates: $HOME/.vscode/extensions/rust-lang.rust-*
